//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wallet2
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> water { get; set; }
        public Nullable<int> gas { get; set; }
        public Nullable<int> electricy { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<int> amount { get; set; }
    }
}
